Fake user data capability extension
trendwerk/faker pull request #25
Opened 2019-01-24 23:07 UTC by 5queezer

Fake user data extension. Ability to create and delete fake users. Fake posts can be assigned to a fake user through a variable. See example in the Readme.

2019-01-28 10:34 UTC, haroldangenent commented
First off, thanks for you contribution to this repo! I didn't get a chance to look at any real logic yet, but I've noticed a few things in this PR at a glance:

- The tests for existing functions seem to fail. All tests should still pass;
- Your newly added features do not seem to include tests. However, we would like all newly added code to have automated tests;
- The package name and homepage of the Composer package seem to be changed. Also, there seems to be a dependency added to the NPM packages and some other unrelated changes to this PR. Could you revert changes to these meta files?
- The coding standard PSR is used for this codebase. I think there's a gulpfile with a tasks that checks the coding standards for you. Could you make sure your changes conform to PSR coding standards?

I think faking users could be a useful feature, thanks again.

2019-01-28 10:35 UTC, haroldangenent requested changes
See review comments above.

2019-01-28 15:02 UTC, 5queezer commented
Hello Harold,

- All tests pass.
- I have included a test feature for _users_. However, I could not test if the posts are assigned to a user. I hope that's good for now.
- I have reverted the composer.json and package.json to their previous state. I also removed the author section in composer.json.
- PSR check was successful

I hope you give green light!

2019-02-04 10:28 UTC, haroldangenent requested changes
Sorry for my late response, unfortunately I have been out sick last week. The PR looks good, thanks for your work on this!

I just have some very minor issues to keep the codebase consistent, but everything seems to work like a charm. The user-post connection test could also be improved, I've added an example on what might work.

2019-02-04 10:28 UTC, haroldangenent commented on .gitignore
> +.idea/
Could you remove `.idea/` from this file? Since it's editor-based, I'd assume this in `.gitignore_global`.

2019-02-04 10:28 UTC, haroldangenent commented on README.md
> +### Users
The placement of this part is strange, because it breaks up the "Attachments" area. Maybe `Users` could be above the `Attachments` heading?

2019-02-04 10:28 UTC, haroldangenent commented on composer.json
> +  "description": "Fake post and user data with WP-CLI.",
Maybe just `Fake data with WP-CLI.`?

2019-02-04 10:28 UTC, haroldangenent commented on init.php
>  <?php
Could you remove coding standard preferences from this file, to keep the changes as clean as possible?

2019-02-04 10:28 UTC, haroldangenent commented on init.php
> +    'shortdesc' => 'Fake post and user data with WP-CLI.',
Maybe also `Fake data with WP-CLI.`?

2019-02-04 10:28 UTC, haroldangenent commented on src/Entity/User.php
> +    public $user_pass; // The plain-text user password.
Could you remove comments from user-properties (they are documented at `wp_insert_user`, which is already in the README).

2019-02-04 10:28 UTC, haroldangenent commented on features/fake-user.feature
> +  Scenario: Generate posts with an user
As you've stated, it's a bit harder to test for post-count by a certain number of users. However, the test below doesn't really test anything other that the other test (post creation is already tested in `fake-post.feature`).

I'm either for removing the test, or actually testing if the fake users actually own 15 posts. Maybe something like this could work?

```
wp post list --author=$(wp user list --meta_key=_fake --format=json --field=ID) --format=count
```

2019-02-05 11:37 UTC, 5queezer commented on .gitignore
> +.idea/
`.idea/` and `package-lock.json` have been removed. `package-lock.json` has not been pushed to the repo.

2019-02-05 11:40 UTC, 5queezer commented on README.md
> +### Users
The _User_ heading has been placed above the _Attachments_ heading.

2019-02-05 11:41 UTC, 5queezer commented on composer.json
> +  "description": "Fake post and user data with WP-CLI.",
Agreed.

2019-02-05 11:43 UTC, 5queezer commented on init.php
> +    'shortdesc' => 'Fake post and user data with WP-CLI.',
It has been modified as well. Sorry for the whitespace modifications. My IDE was doing this and I was not aware of it.

2019-02-05 11:43 UTC, 5queezer commented on src/Entity/User.php
> +    public $user_pass; // The plain-text user password.
The comments have been removed.

2019-02-05 11:46 UTC, 5queezer commented on features/fake-user.feature
> +  Scenario: Generate posts with an user
I tried this but I could not have success. Obviously there is no `--author` parameter, or if it does, it does not process a json array, but a single user id.

I removed that part entirely.

2019-02-05 11:47 UTC, 5queezer commented on init.php
>  <?php
Sorry, I was not aware of this. My IDE does this. The file was reverted to its previous state.

2019-02-08 11:04 UTC, haroldangenent approved these changes
@5queezer This is looking great, thanks for your contribution! I'll create a new release for this, since I'm not planning any maintenance releases in the near future.

2019-02-08 11:04 UTC, merged

2019-02-08 13:22 UTC, 5queezer commented
Thank you for helping me and pointing out the errors!